name: BUild & Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    #- run: npm test
      env:
        CI: true
  
  
  FTP-Deploy-Action:
    name: FTP Deploy
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
      - uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          # FTP server name (you may need to specify a port)
          FTP_SERVER: ftp.ndg.mlh.mybluehost.me
          # FTP account username
          FTP_USERNAME: EMcKenize-McHarg@rrubix.site
          # FTP account password
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          # The local folder to copy, defaults to root project folder
          LOCAL_DIR: build 
         
