name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    #- run: npm test
      env:
        CI: true
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with: 
        # FTP server name (you may need to specify a port)
        ftp_server: rrubix.site
        # FTP account username
        ftp_username: ${{ secrets.FTP_USERNAME }}
        # FTP account password
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        # The local folder to copy, defaults to root project folder
        local_dir: /build 
        # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
